# Generated by Django 3.0.6 on 2020-06-17 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sns', '0003_thread'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='登録日時'),
        ),
        migrations.AddField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=128, null=True, verbose_name='タイトル'),
        ),
    ]
